services:
    mysql:
        image: mysql:8.0
        container_name: mysql-service
        ports:
            - 3306:3306
        volumes:
            - mysql-data:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_USER=${MYSQL_USERNAME}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
        healthcheck:
            test:
                [
                    "CMD",
                    "mysqladmin",
                    "ping",
                    "-h",
                    "localhost",
                    "-u",
                    "${MYSQL_USERNAME}",
                    "-p${MYSQL_PASSWORD}"
                ]
            interval: 10s
            timeout: 5s
            retries: 5

    api-notification:
        build:
            context: .
        container_name: api-notification-service
        depends_on:
            mysql:
                condition: service_healthy
        ports:
            - $DOTNET_API_PORT:8080
        environment:
            - ASPNETCORE_ENVIRONMENT=$ASPNETCORE_ENV
            - ConnectionStrings__Clientes=server=$MYSQL_HOST;port=$MYSQL_PORT;user=$MYSQL_USERNAME;password=$MYSQL_PASSWORD;database=$MYSQL_DATABASE;
            - MinIOConnection__Endpoint=$MINIO_HOST:9000
            - MINIO_HOST=$MINIO_HOST
            - MINIO_DOMAIN =$MINIO_DOMAIN
            - MinIOConnection__AccessKey=${MINIO_ROOT_USER}
            - MinIOConnection__SecretKey=${MINIO_ROOT_PASSWORD}

volumes:
    mysql-data:
